### ISSUE TITLE
Can't crawl gitbucket in docker behind the proxy.(connection refused)

### ISSUE THREAD

**Issue by sho-suzuki** [codelibs/gitbucket-fess-plugin#10]
Hi. I'm using fess 11.1, gitbucket 4.12 and gitbucket-fess-plugin 1.1.1.
I launched docker host and 2 docker container(fess, gitbucket).

I set the crawler parameter as follows

```
url=http://gitbucket:8080/gitbucket/
token=9df26a94da469e68241c5b0f6790443ec7f936de
client.proxyHost=proxy_server
client.proxyPort=proxy_port
```

and then, I run scheduler job and got following error.

fess-crawler.log

```
WARN  Failed to access to http://gitbucket:8080/gitbucket/
org.codelibs.elasticsearch.runner.net.CurlException: Failed to access to http://gitbucket:8080/gitbucket/api/v3/fess/repos
        at org.codelibs.elasticsearch.runner.net.CurlRequest.execute(CurlRequest.java:145) ~[elasticsearch-cluster-runner-5.3.2.0.jar:?]
...
Caused by: org.codelibs.elasticsearch.runner.net.CurlException: Failed to access the response.
        at org.codelibs.elasticsearch.runner.net.CurlRequest$1.onResponse(CurlRequest.java:179) ~[elasticsearch-cluster-runner-5.3.2.0.jar:?]
        at org.codelibs.elasticsearch.runner.net.CurlRequest.execute(CurlRequest.java:143) ~[elasticsearch-cluster-runner-5.3.2.0.jar:?]
        ... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_131]
...
2017-05-30 15:02:42,104 [AVw08iP-f4ysEdHmb2Lr-1] WARN  Token is invalid or no Repository
2017-05-30 15:02:42,114 [AVw08iP-f4ysEdHmb2Lr-1] INFO  Deleted 0 old docs.
2017-05-30 15:02:42,114 [DataStoreCrawler] INFO  [EXEC TIME] crawling time: 5071ms
```

I test a reachability of fess container to gitbucket container and I could connect to the gitbucket service.

```
in fess container
[fess@c02840b8c8e1 logs]$ ping gitbucket
PING gitbucket (172.17.0.9) 56(84) bytes of data.
64 bytes from ktech_gitbucket_1 (172.17.0.9): icmp_seq=1 ttl=64 time=0.490 ms
64 bytes from ktech_gitbucket_1 (172.17.0.9): icmp_seq=2 ttl=64 time=0.135 ms
^C
--- gitbucket ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.135/0.312/0.490/0.178 ms

[fess@c02840b8c8e1 logs]$ telnet gitbucket 8080
Trying 172.17.0.9...
Connected to gitbucket.
Escape character is '^]'.
^CConnection closed by foreign host.

[fess@c02840b8c8e1 logs]$ curl -L "http://gitbucket:8080/gitbucket/"


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>GitBucket</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="icon" href="/gitbucket/assets/common/images/gitbucket.png?20170525203117" type="image/vnd.microsoft.icon" />
...

[fess@c02840b8c8e1 logs]$ curl -L "http://gitbucket:8080/gitbucket/api/v3/fess/repos"
{"message":"Requires authentication"}
```

then, I erased proxy config in crawler but I got same result.
How to fix this problem?

**Comment by marevol** [comment]
```
client.proxyHost=proxy_server
client.proxyPort=proxy_port
```
At the moment, GitBucketDataStore does not support client.proxy*.

**Comment by marevol** [comment]
Fixed in https://github.com/codelibs/fess/issues/1100
