### ISSUE TITLE
Support for GitBucket 4.35.x

### ISSUE THREAD

**Issue by onukura** [codelibs/gitbucket-fess-plugin#34]
With GitBucket 4.35.2, this plugin causes following error.

```
02:36:10.266 [Thread-15] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-fess-plugin_2.13-1.5.0.jar
02:36:10.323 [Thread-15] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-fess-plugin_2.13-1.5.0.jar
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:292)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:284)
	at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistry.scala:209)
	at gitbucket.core.plugin.PluginWatchThread$$anon$2.$anonfun$run$3(PluginRegistry.scala:452)
	at gitbucket.core.plugin.PluginWatchThread$$anon$2.$anonfun$run$3$adapted(PluginRegistry.scala:450)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.plugin.PluginWatchThread$$anon$2.run(PluginRegistry.scala:450)
Caused by: java.lang.AbstractMethodError: Method org/codelibs/gitbucket/fess/controller/FessSearchController.gitbucket$core$service$ActivityService$_setter_$gitbucket$core$service$ActivityService$$formats_$eq(Lorg/json4s/Formats;)V is abstract
	at org.codelibs.gitbucket.fess.controller.FessSearchController.gitbucket$core$service$ActivityService$_setter_$gitbucket$core$service$ActivityService$$formats_$eq(FessSearchController.scala)
	at gitbucket.core.service.ActivityService.$init$(ActivityService.scala:25)
	at org.codelibs.gitbucket.fess.controller.FessSearchController.<init>(FessSearchController.scala:11)
	at Plugin.<init>(Plugin.scala:26)
	... 17 common frames omitted
```

**Comment by onukura** [comment]
@marevol thx for merging my PR!

Do you have plan to release on GitHub [here](https://github.com/codelibs/gitbucket-fess-plugin/releases)?

**Comment by marevol** [comment]
Thank you for your work!
Updated.

**Comment by onukura** [comment]
Thank you!!
