### ISSUE TITLE
Not compatible with gitbucket 4.36.2

### ISSUE THREAD

**Issue by eitsupi** [codelibs/gitbucket-fess-plugin#38]
If you install it on the latest version of GitBucket, 4.36.2, the following screen will be displayed and it will not work properly. 

![image](https://user-images.githubusercontent.com/50911393/132087052-8e4142b7-9135-4b03-92ca-f25a7ba57902.png)

At this time, the following error has occurred (it is the log of the container launched by docker-compose) 

```
gitbucket_1  | 07:30:23.209 [qtp648129364-54] INFO  o.c.g.f.c.FessSearchController - org.json4s.package$.string2JsonInput(Ljava/lang/String;)Lorg/json4s/JsonInput;
gitbucket_1  | java.lang.NoSuchMethodError: org.json4s.package$.string2JsonInput(Ljava/lang/String;)Lorg/json4s/JsonInput;
gitbucket_1  |  at org.codelibs.gitbucket.fess.service.FessSearchService.execSearch(FessSearchService.scala:73)
gitbucket_1  |  at org.codelibs.gitbucket.fess.service.FessSearchService.execSearch$(FessSearchService.scala:61)
gitbucket_1  |  at org.codelibs.gitbucket.fess.controller.FessSearchController.execSearch(FessSearchController.scala:10)
gitbucket_1  |  at org.codelibs.gitbucket.fess.service.FessSearchService.searchCodeOnFess(FessSearchService.scala:219)
gitbucket_1  |  at org.codelibs.gitbucket.fess.service.FessSearchService.searchCodeOnFess$(FessSearchService.scala:212)
gitbucket_1  |  at org.codelibs.gitbucket.fess.controller.FessSearchController.searchCodeOnFess(FessSearchController.scala:10)
gitbucket_1  |  at org.codelibs.gitbucket.fess.controller.FessSearchControllerBase.$anonfun$$init$$1(FessSearchController.scala:78)
```

No error when installing on 4.36.1

![image](https://user-images.githubusercontent.com/50911393/132087062-2faed249-869e-4be7-9107-99858c13ec73.png)

Is this due to the version upgrade of json4s-jackson in the following commit?
https://github.com/gitbucket/gitbucket/commit/838a8d4c7b2bbf8bb4e5a16b476640f6430cb2ec

Thanks.

**Comment by freerider7777** [comment]
Does it work with fresh versions now?
