### ISSUE TITLE
Can not compile gitbucket-fess-plugin

### ISSUE THREAD

**Issue by oomorinobu** [codelibs/gitbucket-fess-plugin#39]
I have tried to build this plugin but have failed.
The cause seems to be the closure of bintray.com, but I don't know how to get around it.
Could you please help me?

SBT RUN
```
$ sbt run 
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/home/xxxxxxxxx/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.6/run_2.12-1.4.6.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] welcome to sbt 1.4.6 (Private Build Java 17.0.3)
[info] loading settings for project gitbucket-fess-plugin-build from plugins.sbt ...
[info] loading project definition from /home/xxxxxxxxx/project/gitbucket-fess-plugin/project
[info] loading settings for project gitbucket-fess-plugin from build.sbt ...
[info] set current project to gitbucket-fess-plugin (in build file:/home/xxxxxxxxx/project/gitbucket-fess-plugin/)
[info] Updating gitbucket-fess-plugin
[info] Resolved gitbucket-fess-plugin dependencies
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     com.github.bkromhout:java-diff-utils:2.1.1:
[error]         download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom) while downloading https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error]         not found:
[error]             /home/xxxxxxxxx/.ivy2/local/com.github.bkromhout/java-diff-utils/2.1.1/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error] (coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     com.github.bkromhout:java-diff-utils:2.1.1:
[error]         download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom) while downloading https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error]         not found:
[error]             /home/xxxxxxxxx/.ivy2/local/com.github.bkromhout/java-diff-utils/2.1.1/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error] Total time: 3 s, completed Jul 9, 2022, 6:53:47 AM
```

SBT EVICTED
```
$ sbt evicted
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/home/xxxxxxxxx/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.6/run_2.12-1.4.6.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] welcome to sbt 1.4.6 (Private Build Java 17.0.3)
[info] loading settings for project gitbucket-fess-plugin-build from plugins.sbt ...
[info] loading project definition from /home/xxxxxxxxx/project/gitbucket-fess-plugin/project
[info] loading settings for project gitbucket-fess-plugin from build.sbt ...
[info] set current project to gitbucket-fess-plugin (in build file:/home/xxxxxxxxx/project/gitbucket-fess-plugin/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.bkromhout:java-diff-utils:2.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/xxxxxxxxx/.ivy2/localcom.github.bkromhout/java-diff-utils/2.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom) while downloading https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (evicted) sbt.librarymanagement.ResolveException: Error downloading com.github.bkromhout:java-diff-utils:2.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/xxxxxxxxx/.ivy2/localcom.github.bkromhout/java-diff-utils/2.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom) while downloading https://dl.bintray.com/bkromhout/maven/com/github/bkromhout/java-diff-utils/2.1.1/java-diff-utils-2.1.1.pom
[error] Total time: 4 s, completed Jul 9, 2022, 6:55:04 AM
```

**Comment by oomorinobu** [comment]
I changed the version of the gitbucket on which it depends and it compiled.

```
build.sbt

gitbucketVersion := "4.37.2"
```
