### ISSUE TITLE
JDBC driver is null

### ISSUE THREAD

**Issue by sho-suzuki** [codelibs/gitbucket-fess-plugin#9]
Hi. I'm using fess 11.1, gitbucket 4.12 and gitbucket-fess-plugin 1.1.1.

I set it according to the tutorial at http://qiita.com/kw_udon/items/06d385b88dafed4bd609.
The following log was output to fess-crawler.log when I ran the scheduler.

```
2017-05-23 11:17:44,395 [AVw08iP-f4ysEdHmb2Lr-1] ERROR Failed to process a data crawling: gitbucket
org.codelibs.fess.exception.DataStoreException: Failed to crawl data in DB.
        at org.codelibs.fess.ds.impl.DatabaseDataStoreImpl.storeData(DatabaseDataStoreImpl.java:166) ~[classes/:?]
        at org.codelibs.fess.ds.impl.AbstractDataStoreImpl.store(AbstractDataStoreImpl.java:106) ~[classes/:?]
        at org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.process(DataIndexHelper.java:236) [classes/:?]
        at org.codelibs.fess.helper.DataIndexHelper$DataCrawlingThread.run(DataIndexHelper.java:222) [classes/:?]
Caused by: org.codelibs.fess.exception.DataStoreException: JDBC driver is null
        at org.codelibs.fess.ds.impl.DatabaseDataStoreImpl.getDriverClass(DatabaseDataStoreImpl.java:58) ~[classes/:?]
        at org.codelibs.fess.ds.impl.DatabaseDataStoreImpl.storeData(DatabaseDataStoreImpl.java:93) ~[classes/:?]
        ... 3 more
2017-05-23 11:17:44,462 [AVw08iP-f4ysEdHmb2Lr-1] INFO  Deleted 0 old docs.
```

**Comment by marevol** [comment]
Could you check Handler Name in your setting?
http://fess.codelibs.org/11.1/admin/dataconfig-guide.html#handler-name
I think you had used DatabaseDataStore, not GitBucketDataStore.

**Comment by sho-suzuki** [comment]
Thank you for your quick reqly. 
You were right.
I checked it again and it was database. 
There is no error of jdbc is null where we fixed to gitbucket.
